openapi: 3.0.0
info:
  title: entertainment App API
  description: entertainment App API
  version: 0.1.9

servers:
  - url: https://entertainment-web-app-api-production-4cd8.up.railway.app
    description: production server
  - url: http://localhost:3000
    description: local server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /api/register:
    post:
      summary: Create new user
      tags:
        - Registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: The email of the user
                password:
                  type: string
                  description: The password of the user
                repeatPassword:
                  type: string
                  description: The repeated password of the user
      responses:
        "200":
          description: User successfully added to the database
        "400":
          description: Bad request, username is required
        "500":
          description: Internal server error

  /api/login:
    post:
      summary: User login
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: The username of the user
                password:
                  type: string
                  description: The password of the user
      responses:
        "422":
          description: User successfully logged in
        "401":
          description: Unauthorized, invalid credentials
        "500":
          description: Internal server error

  /api/allMovies:
    get:
      # security:
      #   - bearerAuth: []
      summary: Retrieve all movies
      tags:
        - Movies
      responses:
        "200":
          description: A list of movies
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                    thumbnail:
                      type: object
                      properties:
                        trending:
                          type: object
                          properties:
                            small:
                              type: string
                            large:
                              type: string
                        regular:
                          type: object
                          properties:
                            small:
                              type: string
                            medium:
                              type: string
                            large:
                              type: string
                    year:
                      type: integer
                    category:
                      type: string
                    rating:
                      type: string
                    isBookmarked:
                      type: boolean
                    isTrending:
                      type: boolean
                    _id:
                      type: string

  paths:
  /api/postBookmark:
    post:
      security:
        - bearerAuth: []
      tags:
        - Bookmark
      summary: Create a new bookmark
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userEmail:
                  type: string
                  description: The ID of the user
                  example: "123456"
                _id:
                  type: []
                  description: The ID of the movie to be bookmarked
                  example: "789012"
      responses:
        "200":
          description: Bookmark created successfully
        "401":
          description: Unauthorized - Title not found or bookmark already exists

  paths:
  /api/bookmarked:
    get:
      summary: Retrieve bookmarked movies
      tags:
        - Movies
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of bookmarked movies
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                    thumbnail:
                      type: object
                      properties:
                        trending:
                          type: object
                          properties:
                            small:
                              type: string
                            large:
                              type: string
                        regular:
                          type: object
                          properties:
                            small:
                              type: string
                            medium:
                              type: string
                            large:
                              type: string
                    year:
                      type: integer
                    category:
                      type: string
                    rating:
                      type: string
                    isBookmarked:
                      type: boolean
                    isTrending:
                      type: boolean
                    _id:
                      type: string
        '401':
          description: Unauthorized - User not authenticated or invalid credentials
